<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5bd1908d-977c-4016-bcec-d9c346fff98e</testSuiteGuid>
   <testCaseLink>
      <guid>88e8a6e1-3a10-4edc-8e1a-c32bded801bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d0f31f2c-bdef-4c90-ac96-c8a0f5ce669e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d0f31f2c-bdef-4c90-ac96-c8a0f5ce669e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>9cf35a9b-f733-4a5e-9aab-85653eca5db2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d0f31f2c-bdef-4c90-ac96-c8a0f5ce669e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>34540b8d-5e15-49ad-ac4d-d92fbe3001a0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
