<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NavigationResult</name>
   <tag></tag>
   <elementGuidId>409e8b2c-d07d-42c0-be7d-2e2fd00b2729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='class-summary.tabpanel']/div/div[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14ff9cf5-addd-4ad3-94e5-838b6896922a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>NavigationResult.html</value>
      <webElementGuid>227759f3-e8a7-43c5-a2ee-7d62a2f70534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.bidi.browsingcontext</value>
      <webElementGuid>117c4a1f-59fd-4426-882d-4f14aebb4a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NavigationResult</value>
      <webElementGuid>7aba871b-451a-4ea3-a985-91b551f48099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-summary.tabpanel&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-first odd-row-color class-summary class-summary-tab2&quot;]/a[1]</value>
      <webElementGuid>2f8e1124-5974-4dff-ae8d-fcae7491cd8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='class-summary.tabpanel']/div/div[9]/a</value>
      <webElementGuid>7b91769d-932c-4751-9193-55a827398674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NavigationResult')]</value>
      <webElementGuid>d2bfe6ad-9272-4115-9bad-c843dc30dd4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NavigationInfo'])[1]/following::a[1]</value>
      <webElementGuid>294d6bd0-9544-4fef-84e3-de60f1b59a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BrowsingContextInfo'])[1]/following::a[2]</value>
      <webElementGuid>a7d161cc-0cd5-4bcb-b235-706b49e704a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ReadinessState'])[1]/preceding::a[1]</value>
      <webElementGuid>a923f5ac-8a7a-4c75-b9c8-701c0be975c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UserPromptClosed'])[1]/preceding::a[2]</value>
      <webElementGuid>6f7ef846-edd4-400f-ac01-e3bf16f061e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NavigationResult']/parent::*</value>
      <webElementGuid>2cf9a0f4-ed18-4b42-8228-8640f99e2966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'NavigationResult.html')]</value>
      <webElementGuid>559e88ff-b72a-4831-be02-59cdf49d7aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/a</value>
      <webElementGuid>9f0bea2e-6488-4cbf-ab14-880e504c8f10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'NavigationResult.html' and @title = 'class in org.openqa.selenium.bidi.browsingcontext' and (text() = 'NavigationResult' or . = 'NavigationResult')]</value>
      <webElementGuid>019c788b-88f8-4e09-a17f-8161de78b18d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
