<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NavigationResult</name>
   <tag></tag>
   <elementGuidId>493d0cd9-2158-43ae-b60a-a1068372c3bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.member-name-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='constructor-summary']/div[2]/div[3]/code/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0c2d039-5448-4b82-98cb-f89c48bc168b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#%3Cinit%3E(java.lang.String,java.lang.String)</value>
      <webElementGuid>70f63b94-e256-426f-9554-130885f389f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>member-name-link</value>
      <webElementGuid>fbf32a53-5b85-4d39-96aa-0ad6bdc33a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NavigationResult</value>
      <webElementGuid>2743ac10-652d-4787-aae3-9a66c0623202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;constructor-summary&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-constructor-name even-row-color&quot;]/code[1]/a[@class=&quot;member-name-link&quot;]</value>
      <webElementGuid>0ef51ad8-ae92-4744-8b02-0306807d6ea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='constructor-summary']/div[2]/div[3]/code/a</value>
      <webElementGuid>b003b2b4-bf1e-4acd-aa4a-bb589feeb6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'NavigationResult')]</value>
      <webElementGuid>0494f2fb-ec38-4ae4-9aa8-f52b52bdaefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::a[1]</value>
      <webElementGuid>32ed5446-e2c6-4f33-9fa6-a1c458d49173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='String'])[1]/preceding::a[1]</value>
      <webElementGuid>a6208fd2-150b-46d4-ac39-4e9cd79e35b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='String'])[2]/preceding::a[2]</value>
      <webElementGuid>283f0d2e-e367-4b68-8515-0dc39a257178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#%3Cinit%3E(java.lang.String,java.lang.String)')]</value>
      <webElementGuid>f3b89b60-0f64-4683-8965-158c9111f029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//code/a</value>
      <webElementGuid>cff074cc-94ce-4602-baff-61449e8709e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#%3Cinit%3E(java.lang.String,java.lang.String)' and (text() = 'NavigationResult' or . = 'NavigationResult')]</value>
      <webElementGuid>9a9d272e-48cf-446d-8ed2-0f06b0fe7818</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
