<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_String</name>
   <tag></tag>
   <elementGuidId>470c10d5-d192-4bf8-8d63-6ed7a2acc87d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='getUrl()']/div/span[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d97541f9-939c-4ff5-9d1d-c8524b637cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html</value>
      <webElementGuid>dc9a7ea6-1528-4c95-897c-6fd929d96436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class or interface in java.lang</value>
      <webElementGuid>0f3a406a-152f-4ad4-a882-dd3292b375fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>external-link</value>
      <webElementGuid>3034a84b-c615-430f-8f21-3e38d4b4dce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>String</value>
      <webElementGuid>fcff2e52-8bec-4249-8654-c707e1e04340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;getUrl()&quot;)/div[@class=&quot;member-signature&quot;]/span[@class=&quot;return-type&quot;]/a[@class=&quot;external-link&quot;]</value>
      <webElementGuid>b14ec3f8-83f3-4094-9a1b-8b7e84361c61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='getUrl()']/div/span[2]/a</value>
      <webElementGuid>0ffaf74c-2bff-4e0e-9354-4a638978a396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'String')])[9]</value>
      <webElementGuid>8d6ecec9-6191-403d-9954-194aac4514d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='public'])[3]/following::a[1]</value>
      <webElementGuid>7e2e37b4-c160-40bf-8c14-015537ba6f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='getUrl'])[3]/preceding::a[1]</value>
      <webElementGuid>352c7089-7360-4cd4-86d6-bb16f7821ef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fromJson'])[2]/preceding::a[1]</value>
      <webElementGuid>aadecd4b-30c9-4489-b3b4-e9405da5d0a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html')])[8]</value>
      <webElementGuid>284fecc1-fe7c-470c-853e-9c997ceaa942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/section/div/span[2]/a</value>
      <webElementGuid>29fd052e-08c6-4cdd-8530-34e100978cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html' and @title = 'class or interface in java.lang' and (text() = 'String' or . = 'String')]</value>
      <webElementGuid>718b4a07-b2dc-427b-8f98-72003f64e5bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
