<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Constable</name>
   <tag></tag>
   <elementGuidId>5a285a17-ea7d-40e2-b061-2f74a14a7067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;interface in java.lang.constant&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='class-description']/dl/dd/code[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b0868f1-f9c8-4a52-bd2e-70ab62bed636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>constant/Constable.html</value>
      <webElementGuid>4a0f2a2f-1b1e-4d08-bf3f-10a263128972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>interface in java.lang.constant</value>
      <webElementGuid>9ba9ec24-d282-4a99-a6a7-9f26573d7abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Constable</value>
      <webElementGuid>62a2849a-496c-422f-b277-e898575b422f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-description&quot;)/dl[@class=&quot;notes&quot;]/dd[1]/code[4]/a[1]</value>
      <webElementGuid>61db1d3a-08bd-41b1-8d06-f3d550476317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='class-description']/dl/dd/code[4]/a</value>
      <webElementGuid>ce66f098-e08c-4644-abd5-1bb0a857abd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Constable')]</value>
      <webElementGuid>b7a0e53a-9c2c-444e-945d-bdf7119bb716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='String'])[1]/following::a[1]</value>
      <webElementGuid>35221d8a-4d27-4904-b23a-87f09683f860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comparable'])[1]/following::a[2]</value>
      <webElementGuid>287e9b0c-43d3-48fd-ba93-e8e6a5448e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ConstantDesc'])[1]/preceding::a[1]</value>
      <webElementGuid>394f5d3b-0c6e-4cdb-b5e4-fa6125690fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='public final class'])[1]/preceding::a[2]</value>
      <webElementGuid>ce9e5c5d-a5ca-4479-a847-c6855b080afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Constable']/parent::*</value>
      <webElementGuid>60ab1aed-8fc3-4798-8d45-e093f7786c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'constant/Constable.html')]</value>
      <webElementGuid>1bfc2fb0-330a-433d-9b24-6994aee58a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//code[4]/a</value>
      <webElementGuid>442a211c-4a09-46d9-960b-39000c4ec7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'constant/Constable.html' and @title = 'interface in java.lang.constant' and (text() = 'Constable' or . = 'Constable')]</value>
      <webElementGuid>13979f19-1dec-403e-bbdc-1284de1622d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
