<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>code_MethodHandleDesc</name>
   <tag></tag>
   <elementGuidId>526915e4-41fb-4e94-a385-85e163a19b67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='class-description']/div[2]/p/a[19]/code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>0089c5a5-8109-42e2-b891-84679c2fd7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MethodHandleDesc</value>
      <webElementGuid>4b53085f-07e4-4c48-9252-11a0b4456a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;class-description&quot;)/div[@class=&quot;block&quot;]/p[1]/a[19]/code[1]</value>
      <webElementGuid>8303879d-fde7-403e-a96f-17c74b321fc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='class-description']/div[2]/p/a[19]/code</value>
      <webElementGuid>f2be5eb9-cdf5-476e-903e-5eebae20cf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MethodTypeDesc'])[1]/following::code[1]</value>
      <webElementGuid>fd5e6607-02fe-4f34-80d4-19e261332e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ClassDesc'])[1]/following::code[2]</value>
      <webElementGuid>d8ae2bca-c8d7-4bd7-bd1b-1f68b9cd8bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ConstantDesc'])[2]/preceding::code[1]</value>
      <webElementGuid>17a0219c-021d-437b-8517-a0c8854a6043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enum'])[1]/preceding::code[2]</value>
      <webElementGuid>2138bd5a-011b-454f-b4f2-7464fde82cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MethodHandleDesc']/parent::*</value>
      <webElementGuid>8b7f3da4-5fe2-4799-8faf-9cf1f0338e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[19]/code</value>
      <webElementGuid>332a66b0-3960-479b-8cc9-1178d8824760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//code[(text() = 'MethodHandleDesc' or . = 'MethodHandleDesc')]</value>
      <webElementGuid>e5fe62c5-13f7-412b-97c6-22b1cd5fae9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
